on: [push]
jobs:
  build_and_static_analysis:
    runs-on: ubuntu-latest
    container:
      image: elena11j/stm32f401re:latest
    env:
      TOOLS_PATH: /home/ubuntu/dev/tools
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: "true"
      - run: make
      - run: make cppcheck